# **Load the Dataset**

In [9]:
# This loads the data so we can work with it
import pandas as pd

# Read the CSV file
df = pd.read_csv('sample_data/Titanic-Dataset.csv')

# Show the first 5 rows
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# **See What's in Your Data**

In [10]:
# Show how many rows and columns
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

# Show column names
print("\nColumn names:")
print(df.columns.tolist())

Rows: 891
Columns: 12

Column names:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

# **Find Problems**

In [11]:
# Check for empty values
print("Empty values in each column:")
print(df.isnull().sum())

# Check for duplicate rows
print("\nDuplicate rows:", df.duplicated().sum())

Empty values in each column:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Duplicate rows: 0

# **Fix Empty Values**

In [12]:
# Fix Age column - fill empty with average age
df['Age'] = df['Age'].fillna(df['Age'].median())

# Fix Cabin column - fill empty with 'Unknown'
df['Cabin'] = df['Cabin'].fillna('Unknown')

# Fix Embarked column - fill empty with most common value
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# Check if all fixed
print("Empty values now:")
print(df.isnull().sum())

Empty values now:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

# **Remove Duplicates**

In [13]:
# Count rows before
before = len(df)

# Remove duplicates
df = df.drop_duplicates()

# Count rows after
after = len(df)

print("Rows before:", before)
print("Rows after:", after)
print("Removed:", before - after)

Rows before: 891
Rows after: 891
Removed: 0

# **Fix Data Types**

In [14]:
# Change Age to whole number
df['Age'] = df['Age'].astype(int)

# Change Sex to category
df['Sex'] = df['Sex'].astype('category')

print("Data types fixed!")
print(df.dtypes)

Data types fixed!
PassengerId       int64
Survived          int64
Pclass            int64
Name             object
Sex            category
Age               int64
SibSp             int64
Parch             int64
Ticket           object
Fare            float64
Cabin            object
Embarked         object
dtype: object

# **Rename Columns**

In [15]:
# Make column names shorter and clearer
df = df.rename(columns={
    'PassengerId': 'ID',
    'SibSp': 'Family',
    'Parch': 'Parents'
})

print("New column names:")
print(df.columns.tolist())

New column names:
['ID', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Family', 'Parents', 'Ticket', 'Fare', 'Cabin', 'Embarked']

# **Check Your Clean Data**

In [16]:
# Show first 5 rows of cleaned data
print("Your cleaned data:")
df.head()

Your cleaned data:

,ID,Survived,Pclass,Name,Sex,Age,Family,Parents,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,Unknown,S

# **Save and Download**

In [17]:
# Save to your computer
df.to_csv('cleaned_titanic.csv', index=False)

# Download the file
from google.colab import files
files.download('cleaned_titanic.csv')

print("✅ File downloaded!")

✅ File downloaded!

# **Quick Summary**

In [18]:
# See some facts about your data
total = len(df)
survived = df['Survived'].sum()
rate = (survived / total) * 100

print("="*40)
print("FACTS ABOUT TITANIC")
print("="*40)
print(f"Total passengers: {total}")
print(f"Survived: {survived} ({rate:.1f}%)")

# Survival by gender
men = df[df['Sex'] == 'male']
women = df[df['Sex'] == 'female']
men_survived = men['Survived'].sum()
women_survived = women['Survived'].sum()

print(f"\nMen: {len(men)} passengers, {men_survived} survived ({men_survived/len(men)*100:.1f}%)")
print(f"Women: {len(women)} passengers, {women_survived} survived ({women_survived/len(women)*100:.1f}%)")

========================================
FACTS ABOUT TITANIC
========================================
Total passengers: 891
Survived: 342 (38.4%)

Men: 577 passengers, 109 survived (18.9%)
Women: 314 passengers, 233 survived (74.2%)